"""TOML-backed config for html-mcp.

Mirrors model_switch/store.py's discipline:

  - Unknown top-level keys land in ``Config.extra_top``.
  - Unknown ``[auth]`` keys land in ``Config.extra_auth``.
  - Both are round-tripped verbatim on save — adding new fields (ours or
    a future third party's) never silently drops them.

Atomic writes (``.tmp`` then ``os.replace``), ``chmod 0600`` on save
(token is a credential).
"""
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional

from html_mcp._compat import toml_dump, toml_loads


# Fields html-mcp owns at the top level. Anything else round-trips via
# ``extra_top``.
_TOP_LEVEL_FIELDS = (
    "host",
    "port",
    "docroot",
    "public_base_url",
    "max_file_size",
)
# Fields html-mcp owns under [auth]. Anything else round-trips via
# ``extra_auth``.
_AUTH_FIELDS = ("token",)


class ConfigError(Exception):
    """Base for config-level errors."""


class MissingConfigFile(ConfigError):
    """The config file does not exist (caller should run `html-mcp init`)."""


class InvalidConfig(ConfigError):
    """A config field has an invalid value."""


@dataclass
class Config:
    host: str = "127.0.0.1"
    port: int = 8765
    docroot: str = "/var/www/notes"
    public_base_url: str = "https://notes.example.com"
    max_file_size: int = 52428800  # 50 MB
    # [auth].token — auto-generated by `init`; required by `serve`.
    token: Optional[str] = None
    # Unknown top-level keys, preserved on save.
    extra_top: Dict[str, Any] = field(default_factory=dict)
    # Unknown [auth] keys, preserved on save.
    extra_auth: Dict[str, Any] = field(default_factory=dict)

    def to_toml_dict(self) -> Dict[str, Any]:
        """Serialize as a dict in canonical load order, with extras appended."""
        out: Dict[str, Any] = dict(self.extra_top)
        out["host"] = self.host
        out["port"] = self.port
        out["docroot"] = self.docroot
        out["public_base_url"] = self.public_base_url
        out["max_file_size"] = self.max_file_size
        if self.token is not None or self.extra_auth:
            auth: Dict[str, Any] = dict(self.extra_auth)
            if self.token is not None:
                auth["token"] = self.token
            out["auth"] = auth
        return out


def load_config(path: Path) -> Config:
    """Load ``config.toml``. Missing file -> ``MissingConfigFile``."""
    if not path.exists():
        raise MissingConfigFile(
            "config not found at {}; run `html-mcp init` first".format(path)
        )
    raw = toml_loads(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ConfigError(
            "config.toml root must be a table, got: {!r}".format(type(raw))
        )

    cfg = Config()

    # Validate types of owned top-level fields.
    if "host" in raw and not isinstance(raw["host"], str):
        raise InvalidConfig("host must be a string")
    if "port" in raw and not isinstance(raw["port"], int):
        raise InvalidConfig("port must be an integer")
    if "docroot" in raw and not isinstance(raw["docroot"], str):
        raise InvalidConfig("docroot must be a string")
    if "public_base_url" in raw and not isinstance(raw["public_base_url"], str):
        raise InvalidConfig("public_base_url must be a string")
    if "max_file_size" in raw and not isinstance(raw["max_file_size"], int):
        raise InvalidConfig("max_file_size must be an integer")

    # Pull owned fields + collect extras.
    for k, v in raw.items():
        if k in _TOP_LEVEL_FIELDS:
            setattr(cfg, k, v)
        elif k == "auth":
            continue  # handled below
        else:
            cfg.extra_top[k] = v

    auth_raw = raw.get("auth")
    if auth_raw is not None:
        if not isinstance(auth_raw, dict):
            raise InvalidConfig("[auth] must be a table, got: {!r}".format(type(auth_raw)))
        if "token" in auth_raw and not isinstance(auth_raw["token"], str):
            raise InvalidConfig("[auth].token must be a string")
        for k, v in auth_raw.items():
            if k in _AUTH_FIELDS:
                setattr(cfg, k, v)
            else:
                cfg.extra_auth[k] = v

    return cfg


def save_config(path: Path, cfg: Config) -> None:
    """Atomic write of ``config.toml``. chmod 0600 (token is a credential)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    raw = cfg.to_toml_dict()
    tmp = path.with_suffix(path.suffix + ".tmp")
    with open(tmp, "w", encoding="utf-8") as f:
        toml_dump(raw, f)
    os.chmod(tmp, 0o600)
    os.replace(tmp, path)


def validate_for_serve(cfg: Config) -> None:
    """Validate that ``cfg`` is suitable for `serve`.

    Raises ``InvalidConfig`` if any field has an unusable value. Callers
    (the daemon) should fail fast on this.
    """
    if not (1 <= cfg.port <= 65535):
        raise InvalidConfig("port must be in 1..65535, got: {}".format(cfg.port))
    if cfg.max_file_size <= 0:
        raise InvalidConfig(
            "max_file_size must be positive, got: {}".format(cfg.max_file_size)
        )
    if not cfg.docroot:
        raise InvalidConfig("docroot must be a non-empty string")
    if not cfg.public_base_url:
        raise InvalidConfig("public_base_url must be a non-empty string")
    if cfg.token is None:
        raise InvalidConfig(
            "auth.token is missing; run `html-mcp token rotate` (or re-init)"
        )